from __future__ import annotations
"""Словарь сопоставлений названий колонок EN ↔ RU для маркетинговых, продажных и финансовых баз данных.
Используется ассистентом для понимания структуры данных на обоих языках.
"""

# Основной словарь: английское название → русское название + синонимы
COLUMN_TRANSLATIONS = {
    # === ДАТЫ И ВРЕМЯ ===
    "date": "дата",
    "date_of_sale": "дата продажи",
    "date_of_sold": "дата продажи",
    "purchase_date": "дата покупки",
    "order_date": "дата заказа",
    "created_at": "дата создания",
    "updated_at": "дата обновления",
    "delivery_date": "дата доставки",
    "payment_date": "дата оплаты",
    "invoice_date": "дата счета",
    "timestamp": "временная метка",
    "start_date": "дата начала",
    "end_date": "дата окончания",
    "reporting_date": "дата отчета",
    "transaction_date": "дата транзакции",
    "sale_date": "дата продажи",
    "ship_date": "дата отгрузки",
    "due_date": "срок оплаты",
    "expiration_date": "срок годности",
    "birth_date": "дата рождения",
    "hire_date": "дата найма",
    "close_date": "дата закрытия",
    "open_date": "дата открытия",
    "first_order": "первый заказ",
    "last_order": "последний заказ",
    "date_price_change": "дата изменения цены",

    # === ДЕНЕЖНЫЕ ПОКАЗАТЕЛИ ===
    "revenue": "выручка",
    "sales_amount": "сумма продаж",
    "total_sales": "общие продажи",
    "net_sales": "чистые продажи",
    "gross_sales": "валовые продажи",
    "profit": "прибыль",
    "net_profit": "чистая прибыль",
    "gross_profit": "валовая прибыль",
    "operating_profit": "операционная прибыль",
    "margin": "маржа",
    "margin_pct": "маржа %",
    "profit_margin": "маржа прибыли",
    "markup": "наценка",
    "cost": "себестоимость",
    "cost_price": "закупочная цена",
    "unit_cost": "стоимость единицы",
    "price": "цена",
    "unit_price": "цена за единицу",
    "retail_price": "розничная цена",
    "wholesale_price": "оптовая цена",
    "list_price": "_catalogная цена",
    "sale_price": "цена со скидкой",
    "discount": "скидка",
    "discount_pct": "скидка %",
    "discount_amount": "сумма скидки",
    "tax": "налог",
    "tax_rate": "ставка налога",
    "vat": "НДС",
    "shipping_cost": "стоимость доставки",
    "total": "итого",
    "amount": "сумма",
    "balance": "баланс",
    "budget": "бюджет",
    "forecast": "прогноз",
    "target": "целевой показатель",
    "quota": "квота",
    "commission": "комиссия",
    "fee": "комиссия/сбор",
    "penalty": "штраф",
    "refund": "возврат",
    "credit": "кредит",
    "debit": "дебет",
    "investment": "инвестиция",
    "roi": "ROI",
    "romi": "ROMI",
    "cac": "CAC (стоимость привлечения клиента)",
    "ltv": "LTV (пожизненная ценность клиента)",
    "arpu": "ARPU (средний доход на пользователя)",
    "aov": "AOV (средний чек)",
    "avg_check": "средний чек",
    "avg_order_value": "средняя стоимость заказа",
    "conversion_rate": "конверсия",
    "churn_rate": "отток клиентов",
    "retention_rate": "удержание клиентов",
    "new_price": "новая цена",
    "old_price": "старая цена",
    "markup_pct": "наценка %",

    # === КОЛИЧЕСТВА ===
    "quantity": "количество",
    "qty": "количество",
    "quantity_sold": "количество проданных",
    "quantity_in_stock": "количество на складе",
    "stock": "остаток",
    "stock_quantity": "количество на складе",
    "inventory": "инвентарь/запас",
    "units_sold": "продано единиц",
    "units_returned": "возвращено единиц",
    "order_count": "количество заказов",
    "transaction_count": "количество транзакций",
    "customer_count": "количество клиентов",
    "visit_count": "количество визитов",
    "click_count": "количество кликов",
    "impression_count": "количество показов",
    "product_count": "количество товаров",
    "items_count": "количество позиций",
    "count": "количество",
    "total_count": "общее количество",
    "volume": "объем",
    "weight": "вес",
    "size": "размер",

    # === ИДЕНТИФИКАТОРЫ ===
    "id": "ID",
    "order_id": "номер заказа",
    "purchase_id": "номер покупки",
    "transaction_id": "номер транзакции",
    "invoice_id": "номер счета",
    "customer_id": "ID клиента",
    "client_id": "ID клиента",
    "user_id": "ID пользователя",
    "product_id": "ID товара",
    "item_id": "ID позиции",
    "sku": "SKU (артикул)",
    "sku_code": "артикул",
    "article": "артикул",
    "barcode": "штрих-код",
    "ean": "EAN (европейский товарный номер)",
    "upc": "UPC (универсальный товарный код)",
    "batch_number": "номер партии",
    "serial_number": "серийный номер",
    "store_id": "ID магазина",
    "shop_id": "ID магазина",
    "outlet_id": "ID точки продаж",
    "channel_id": "ID канала",
    "campaign_id": "ID кампании",
    "category_id": "ID категории",
    "supplier_id": "ID поставщика",
    "manufacturer_id": "ID производителя",
    "brand_id": "ID бренда",
    "employee_id": "ID сотрудника",
    "manager_id": "ID менеджера",
    "department_id": "ID отдела",
    "region_id": "ID региона",
    "session_id": "ID сессии",

    # === НАЗВАНИЯ И ТЕКСТ ===
    "name": "название",
    "product_name": "название товара",
    "item_name": "название позиции",
    "customer_name": "имя клиента",
    "client_name": "имя клиента",
    "company_name": "название компании",
    "brand_name": "название бренда",
    "brand": "бренд",
    "manufacturer_name": "название производителя",
    "manufacturer": "производитель",
    "supplier_name": "название поставщика",
    "supplier": "поставщик",
    "store_name": "название магазина",
    "shop_name": "название магазина",
    "outlet_name": "название точки продаж",
    "manager_name": "имя менеджера",
    "manager": "менеджер",
    "employee_name": "имя сотрудника",
    "employee": "сотрудник",
    "user_name": "имя пользователя",
    "username": "логин",
    "description": "описание",
    "comment": "комментарий",
    "notes": "примечания",
    "address": "адрес",
    "city": "город",
    "region": "регион",
    "country": "страна",
    "made_in_country": "страна производства",
    "origin": "происхождение",
    "zip_code": "индекс",
    "postal_code": "почтовый индекс",
    "phone": "телефон",
    "email": "электронная почта",
    "website": "веб-сайт",
    "contact": "контакт",
    "title": "заголовок",
    "subject": "тема",
    "message": "сообщение",
    "text": "текст",
    "label": "метка",
    "tag": "тег",
    "reference": "ссылка/референс",
    "ref_number": "номер ссылки",
    "order_number": "номер заказа",
    "invoice_number": "номер счета",
    "contract_number": "номер договора",

    # === КАТЕГОРИИ И КЛАССИФИКАЦИЯ ===
    "category": "категория",
    "subcategory": "подкатегория",
    "type": "тип",
    "subtype": "подтип",
    "status": "статус",
    "state": "состояние",
    "stage": "этап",
    "priority": "приоритет",
    "level": "уровень",
    "grade": "класс/grade",
    "class": "класс",
    "segment": "сегмент",
    "group": "группа",
    "department": "отдел/департамент",
    "division": "подразделение",
    "channel": "канал",
    "source": "источник",
    "medium": "носитель",
    "campaign": "кампания",
    "initiative": "инициатива",
    "project": "проект",
    "service": "услуга",
    "product_type": "тип товара",
    "payment_method": "способ оплаты",
    "payment_type": "тип оплаты",
    "delivery_method": "способ доставки",
    "shipping_method": "способ отгрузки",
    "warehouse": "склад",
    "location": "местоположение",
    "point_of_sale": "точка продаж",
    "outlet": "точка продаж",
    "store": "магазин",
    "shop": "магазин",
    "branch": "филиал",
    "office": "офис",
    "territory": "территория",
    "zone": "зона",
    "district": "район",
    "area": "район/область",
    "made_in": "страна производства",
    "color": "цвет",
    "material": "материал",
    "composition": "состав",
    "sex": "пол",
    "gender": "пол",
    "age_group": "возрастная группа",
    "size_group": "размерная группа",
    "season": "сезон",
    "collection": "коллекция",
    "model": "модель",
    "version": "версия",
    "edition": "издание",
    "classifier": "классификатор",

    # === ПОКАЗАТЕЛИ ПРОДАЖ ===
    "sales": "продажи",
    "sales_volume": "объем продаж",
    "sales_target": "план продаж",
    "sales_quota": "квота продаж",
    "sales_funnel": "воронка продаж",
    "pipeline": "воронка/конвейер",
    "leads": "лиды",
    "opportunities": "сделки/возможности",
    "deals": "сделки",
    "prospects": "перспективы",
    "contacts": "контакты",
    "accounts": "аккаунты",
    "contracts": "договоры",
    "subscriptions": "подписки",
    "renewals": "продления",
    "upsell": "апсейл",
    "cross_sell": "кросс-сейл",
    "win_rate": "конверсия в сделку",
    "loss_rate": "процент проигрыша",
    "close_rate": "процент закрытия",
    "average_deal_size": "средний размер сделки",
    "sales_cycle_length": "длина цикла продаж",
    "first_response_time": "время первого ответа",
    "resolution_time": "время решения",
    "ticket_volume": "количество тикетов",
    "nps": "NPS (индекс лояльности)",
    "csat": "CSAT (удовлетворенность клиентов)",
    "ces": "CES (усилие клиента)",

    # === МАРКЕТИНГ ===
    "impressions": "показы",
    "clicks": "клики",
    "ctr": "CTR (кликабельность)",
    "cpc": "CPC (стоимость клика)",
    "cpm": "CPM (стоимость 1000 показов)",
    "cpa": "CPA (стоимость действия)",
    "cpl": "CPL (стоимость лида)",
    "cpo": "CPO (стоимость заказа)",
    "roas": "ROAS (возврат рекламных расходов)",
    "spend": "расходы",
    "ad_spend": "расходы на рекламу",
    "marketing_budget": "маркетинговый бюджет",
    "organic_traffic": "органический трафик",
    "paid_traffic": "платный трафик",
    "referral_traffic": "реферальный трафик",
    "direct_traffic": "прямой трафик",
    "bounce_rate": "показатель отказов",
    "session_duration": "длительность сессии",
    "page_views": "просмотры страниц",
    "unique_visitors": "уникальные посетители",
    "new_users": "новые пользователи",
    "returning_users": "возвращающиеся пользователи",
    "engagement_rate": "вовлеченность",
    "share_of_voice": "доля голоса",
    "brand_awareness": "осведомленность о бренде",
    "reach": "охват",
    "frequency": "частота",
    "grps": "GRP (рейтинг gross)",

    # === ФИНАНСЫ ===
    "cash_flow": "денежный поток",
    "operating_expenses": "операционные расходы",
    "opex": "OPEX",
    "capex": "CAPEX (капитальные затраты)",
    "ebitda": "EBITDA",
    "gross_margin": "валовая маржа",
    "net_margin": "чистая маржа",
    "operating_margin": "операционная маржа",
    "debt": "долг",
    "accounts_receivable": "дебиторская задолженность",
    "accounts_payable": "кредиторская задолженность",
    "equity": "капитал",
    "assets": "активы",
    "liabilities": "обязательства",
    "revenue_growth": "рост выручки",
    "profit_growth": "рост прибыли",
    "cogs": "COGS (себестоимость проданных товаров)",
    "sga": "SG&A (коммерческие расходы)",
    "depreciation": "амортизация",
    "amortization": "амортизация",
    "interest": "проценты",
    "taxes": "налоги",
    "dividend": "дивиденды",
    "earnings": "прибыль/доход",
    "eps": "EPS (прибыль на акцию)",
    "pe_ratio": "P/E (соотношение цена/прибыль)",
    "current_ratio": "текущий коэффициент",
    "quick_ratio": "быстрый коэффициент",
    "debt_ratio": "коэффициент задолженности",
    "inventory_turnover": "оборачиваемость запасов",
    "receivable_turnover": "оборачиваемость дебиторки",
    "payable_turnover": "оборачиваемость кредиторки",
    "cash_conversion_cycle": "цикл конвертации денег",

    # === ЛОГИСТИКА И СКЛАД ===
    "warehouse_stock": "складской запас",
    "safety_stock": "страховой запас",
    "reorder_point": "точка перезаказа",
    "lead_time": "срок поставки",
    "delivery_time": "время доставки",
    "shipping_time": "время отгрузки",
    "transit_time": "время в пути",
    "order_fulfillment": "выполнение заказа",
    "fill_rate": "процент выполнения",
    "backorder": "невыполненный заказ",
    "return_rate": "процент возвратов",
    "returns": "возвраты",
    "damaged": "поврежденные",
    "defective": "дефектные",
    "shipped": "отгружено",
    "delivered": "доставлено",
    "pending": "в ожидании",
    "processing": "в обработке",
    "cancelled": "отменено",
    "completed": "завершено",
    "in_transit": "в пути",
    "out_for_delivery": "передано в доставку",

    # === КЛИЕНТЫ ===
    "customer_segment": "сегмент клиента",
    "customer_type": "тип клиента",
    "loyalty_score": "оценка лояльности",
    "lifetime_value": "пожизненная ценность",
    "acquisition_cost": "стоимость привлечения",
    "first_purchase": "первая покупка",
    "last_purchase": "последняя покупка",
    "purchase_frequency": "частота покупок",
    "average_order_value": "средняя стоимость заказа",
    "total_spent": "общая сумма покупок",
    "visit_frequency": "частота визитов",
    "recency": "давность последней покупки",
    "monetary": "денежная ценность",
    "frequency_score": "оценка частоты",
    "rfm_score": "RFM оценка",
    "vip": "VIP статус",
    "membership": "членство",
    "subscription_type": "тип подписки",
    "plan": "тарифный план",
    "tier": "уровень/ранг",
    "rank": "рейтинг",
    "rating": "оценка",
    "review": "отзыв",
    "feedback": "обратная связь",
    "satisfaction": "удовлетворенность",
    "sentiment": "тональность",
}

# Обратный словарь: русское название → английское название
REVERSE_TRANSLATIONS = {v.lower(): k for k, v in COLUMN_TRANSLATIONS.items()}

# Синонимы колонок: альтернативные названия → каноническое английское название
COLUMN_SYNONYMS = {
    # Даты
    "дата": "date",
    "дата продажи": "date_of_sale",
    "дата покупки": "purchase_date",
    "дата заказа": "order_date",
    "дата создания": "created_at",
    "дата обновления": "updated_at",
    "дата доставки": "delivery_date",
    "дата оплаты": "payment_date",
    "дата счета": "invoice_date",
    "время": "timestamp",
    "дата начала": "start_date",
    "дата окончания": "end_date",
    "дата транзакции": "transaction_date",
    "дата отгрузки": "ship_date",
    "срок оплаты": "due_date",
    "срок годности": "expiration_date",
    "дата рождения": "birth_date",
    "дата найма": "hire_date",
    "дата закрытия": "close_date",
    "дата открытия": "open_date",
    "первый заказ": "first_order",
    "последний заказ": "last_order",

    # Деньги
    "выручка": "revenue",
    "продажи": "sales",
    "сумма продаж": "sales_amount",
    "общие продажи": "total_sales",
    "чистые продажи": "net_sales",
    "валовые продажи": "gross_sales",
    "прибыль": "profit",
    "чистая прибыль": "net_profit",
    "валовая прибыль": "gross_profit",
    "операционная прибыль": "operating_profit",
    "маржа": "margin",
    "наценка": "markup",
    "себестоимость": "cost",
    "закупочная цена": "cost_price",
    "цена": "price",
    "розничная цена": "retail_price",
    "оптовая цена": "wholesale_price",
    "скидка": "discount",
    "налог": "tax",
    "НДС": "vat",
    "стоимость доставки": "shipping_cost",
    "итого": "total",
    "сумма": "amount",
    "баланс": "balance",
    "бюджет": "budget",
    "прогноз": "forecast",
    "целевой показатель": "target",
    "квота": "quota",
    "комиссия": "commission",
    "возврат": "refund",
    "кредит": "credit",
    "дебет": "debit",
    "инвестиция": "investment",
    "средний чек": "avg_check",
    "конверсия": "conversion_rate",
    "отток": "churn_rate",
    "удержание": "retention_rate",

    # Количество
    "количество": "quantity",
    "кол-во": "quantity",
    "кол": "quantity",
    "шт": "quantity",
    "штуки": "quantity",
    "единицы": "quantity",
    "продано": "units_sold",
    "возвращено": "units_returned",
    "заказы": "order_count",
    "транзакции": "transaction_count",
    "клиенты": "customer_count",
    "визиты": "visit_count",
    "клики": "clicks",
    "показы": "impressions",
    "товары": "product_count",
    "позиции": "items_count",
    "объем": "volume",
    "вес": "weight",
    "размер": "size",
    "остаток": "stock",
    "запас": "inventory",

    # Идентификаторы
    "номер заказа": "order_id",
    "номер покупки": "purchase_id",
    "номер транзакции": "transaction_id",
    "номер счета": "invoice_id",
    "клиент": "customer_id",
    "пользователь": "user_id",
    "товар": "product_id",
    "артикул": "sku_code",
    "штрих-код": "barcode",
    "магазин": "store_id",
    "точка продаж": "outlet_id",
    "канал": "channel_id",
    "кампания": "campaign_id",
    "категория": "category_id",
    "поставщик": "supplier_id",
    "производитель": "manufacturer_id",
    "бренд": "brand_id",
    "сотрудник": "employee_id",
    "менеджер": "manager_id",
    "отдел": "department_id",
    "регион": "region_id",

    # Названия
    "название": "name",
    "имя": "name",
    "наименование": "name",
    "товар": "product_name",
    "клиент": "customer_name",
    "компания": "company_name",
    "бренд": "brand_name",
    "производитель": "manufacturer_name",
    "поставщик": "supplier_name",
    "магазин": "store_name",
    "менеджер": "manager_name",
    "сотрудник": "employee_name",
    "описание": "description",
    "комментарий": "comment",
    "примечания": "notes",
    "адрес": "address",
    "город": "city",
    "страна": "country",
    "страна производства": "made_in_country",
    "индекс": "zip_code",
    "телефон": "phone",
    "почта": "email",
    "email": "email",
    "сайт": "website",
    "контакт": "contact",
    "заголовок": "title",
    "тема": "subject",

    # Категории
    "категория": "category",
    "подкатегория": "subcategory",
    "тип": "type",
    "статус": "status",
    "состояние": "state",
    "этап": "stage",
    "приоритет": "priority",
    "уровень": "level",
    "класс": "class",
    "сегмент": "segment",
    "группа": "group",
    "отдел": "department",
    "канал": "channel",
    "источник": "source",
    "кампания": "campaign",
    "проект": "project",
    "услуга": "service",
    "склад": "warehouse",
    "адрес": "location",
    "точка продаж": "point_of_sale",
    "филиал": "branch",
    "цвет": "color",
    "материал": "material",
    "состав": "composition",
    "пол": "sex",
    "сезон": "season",
    "коллекция": "collection",
    "модель": "model",

    # Продажи
    "продажи": "sales",
    "объем продаж": "sales_volume",
    "план продаж": "sales_target",
    "воронка": "sales_funnel",
    "лиды": "leads",
    "сделки": "deals",
    "контакты": "contacts",
    "договоры": "contracts",
    "подписки": "subscriptions",
    "конверсия в сделку": "win_rate",

    # Маркетинг
    "показы": "impressions",
    "клики": "clicks",
    "расходы": "spend",
    "расходы на рекламу": "ad_spend",
    "бюджет": "marketing_budget",
    "отказы": "bounce_rate",
    "длительность сессии": "session_duration",
    "просмотры": "page_views",
    "посетители": "unique_visitors",
    "новые пользователи": "new_users",
    "охват": "reach",
    "частота": "frequency",

    # Финансы
    "денежный поток": "cash_flow",
    "операционные расходы": "operating_expenses",
    "капитальные затраты": "capex",
    "валовая маржа": "gross_margin",
    "чистая маржа": "net_margin",
    "долг": "debt",
    "дебиторка": "accounts_receivable",
    "кредиторка": "accounts_payable",
    "капитал": "equity",
    "активы": "assets",
    "обязательства": "liabilities",
    "амортизация": "depreciation",
    "проценты": "interest",
    "налоги": "taxes",
    "дивиденды": "dividend",
    "прибыль на акцию": "eps",

    # Логистика
    "складской запас": "warehouse_stock",
    "страховой запас": "safety_stock",
    "срок поставки": "lead_time",
    "время доставки": "delivery_time",
    "выполнение заказа": "order_fulfillment",
    "процент возвратов": "return_rate",
    "возвраты": "returns",
    "поврежденные": "damaged",
    "дефектные": "defective",
    "отгружено": "shipped",
    "доставлено": "delivered",
    "в ожидании": "pending",
    "отменено": "cancelled",
    "завершено": "completed",

    # Клиенты
    "сегмент клиента": "customer_segment",
    "тип клиента": "customer_type",
    "лояльность": "loyalty_score",
    "пожизненная ценность": "lifetime_value",
    "стоимость привлечения": "acquisition_cost",
    "первая покупка": "first_purchase",
    "последняя покупка": "last_purchase",
    "частота покупок": "purchase_frequency",
    "средняя стоимость заказа": "average_order_value",
    "общая сумма покупок": "total_spent",
    "давность": "recency",
    "рейтинг": "rating",
    "отзыв": "review",
    "обратная связь": "feedback",
    "удовлетворенность": "satisfaction",
}


def get_column_mapping_hint(available_columns: list[str]) -> str:
    """Generate a hint for the LLM about column name mappings based on available columns."""
    hints = []
    for col in available_columns:
        col_lower = col.lower().strip()
        # Check direct translations
        if col_lower in COLUMN_TRANSLATIONS:
            ru_name = COLUMN_TRANSLATIONS[col_lower]
            hints.append(f"{col} = {ru_name}")
        # Check reverse translations
        elif col_lower in REVERSE_TRANSLATIONS:
            en_name = REVERSE_TRANSLATIONS[col_lower]
            hints.append(f"{col} = {en_name}")
        # Check synonyms
        elif col_lower in COLUMN_SYNONYMS:
            canonical = COLUMN_SYNONYMS[col_lower]
            if canonical in COLUMN_TRANSLATIONS:
                hints.append(f"{col} = {COLUMN_TRANSLATIONS[canonical]} ({canonical})")
    
    return "; ".join(hints) if hints else ""


def translate_column_name(name: str) -> str | None:
    """Translate a column name between English and Russian."""
    name_lower = name.lower().strip()
    
    # Try direct translation
    if name_lower in COLUMN_TRANSLATIONS:
        return COLUMN_TRANSLATIONS[name_lower]
    
    # Try reverse translation
    if name_lower in REVERSE_TRANSLATIONS:
        return REVERSE_TRANSLATIONS[name_lower]
    
    # Try synonyms
    if name_lower in COLUMN_SYNONYMS:
        canonical = COLUMN_SYNONYMS[name_lower]
        return COLUMN_TRANSLATIONS.get(canonical, canonical)
    
    return None
